name: Build My React App

on:
  push:
    branches: [ main ]

jobs:
  build-react-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.1.0
      - name: Setup Node JS
        uses: actions/setup-node@v6.5.0
        with:
          node-verions: 22.x
      - name: Install Dependencies
        run: npm install
      - name: Build React App
        run: npm run build
